### ISSUE TITLE
Repositório no GitHub fica com a linguagem marcada como TeX

### ISSUE THREAD

**Issue by Bemesko** [Pibaska/NBA-Basketball-Prediction#2]
![image](https://user-images.githubusercontent.com/55760760/102557287-892cd700-40a9-11eb-8baa-18033d02d766.png)
Acho que seria melhor a gente pegar e fazer um .gitattributes pra mudar a linguagem pra Python, já que é o maior foco do projeto (ou então pedir pro identificador de linguagem do GitHub ignorar o arquivo .tex que a gente tem, mas não sei se dá pra fazer isso).

...Sim, isso demoraria 2 segundos mas eu tô trabalhando em outra coisa agora e não queria esquecer.

**Comment by jvwaldrich0** [comment]
Beleza, vou trabalhar nisso ainda

**Comment by Bemesko** [comment]
Tá meio ruim de resolver isso aqui, ele tá igual mas não sei se eu fiz errado ou se ele só tá processando
